Numpy-on kívül is van lehetőség fix típusú tömb létrehozására.

In [6]:
import array
L = list(range(10))
A = array.array('i', L) # az 'i' az array típusára utal, itt integer
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np

## Lehetőségek tömbök létrehozására
1. listából
1. teljes 0
1. teljes 1
1. ugyanazzal az értékkel
1. lineáris szekvencia
1. random értékek


### 1. Listából

In [10]:
K = np.array([1, 5, 6, 2])
[type(item) for item in K]

[numpy.int32, numpy.int32, numpy.int32, numpy.int32]

In [11]:
# összes elemet "felfelé" húzza, ha van közte pl. egy float is
L = np.array([3.14, 5, 6])
[type(item) for item in L]

[numpy.float64, numpy.float64, numpy.float64]

In [14]:
# specifikálás, hogy milyen adattípus legyen
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [24]:
# többdimenziós lista
# Return an object that produces a sequence of integers from start (inclusive)
# to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
# start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
# These are exactly the valid indices for a list of 4 elements.
# When step is given, it specifies the increment (or decrement).
np.array([range(i, i + 10) for i in [1, 5, 10, 15]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

### 2. Teljes 0

In [36]:
np.zeros((3, 5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### 3. Teljes 1

In [40]:
np.ones((2,3), dtype = 'float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

### 4. Ugyanazzal az értékkel

In [42]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

### 5. Lineáris szekvencia

In [58]:
# fixált lépésköz
L = np.arange(1, 20, 2)
L

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [59]:
np.size(L)

10

In [68]:
# fixált tartomány, hány részre
# benne van az eleje és a vége is!
np.linspace(1, 5, 3)

array([1., 3., 5.])

### 6. Random

In [71]:
np.random.random((3, 3))

array([[0.94955286, 0.89888076, 0.72551427],
       [0.23530762, 0.81325586, 0.81304985],
       [0.75097319, 0.71181495, 0.74558527]])

In [75]:
# random normál eloszlás
# 0 medián, 1 standard deviáció
np.random.normal(0, 1, (3, 3))

array([[ 0.36476998,  0.70086663,  1.27309004],
       [-0.48346013,  0.56254073, -0.23390739],
       [-1.15549549,  0.09027314,  0.5330942 ]])

In [76]:
# 0 és 10 közé random számok, ugyanúgy 3x3 mátrixban
np.random.randint(0, 10, (3, 3))

array([[1, 9, 8],
       [1, 0, 6],
       [3, 5, 4]])

In [87]:
# most legyen az a feladat, hogy az első sor random, a második sor viszont csupa 1-es
L = np.random.randint(0, 10, (1, 5))
M = np.ones((1, 5), dtype = 'int')
np.concatenate((L, M))

array([[7, 9, 8, 6, 4],
       [1, 1, 1, 1, 1]])

In [92]:
# egységmátrix
np.eye(3,3, dtype = 'int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [102]:
# nem inicializált, memóriából éppen ami van
# ezt még nem teljesen értem, erre még vissza kell térni
np.empty(8)

array([ 2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])